name: Discord Bot
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '15 15/6 * * *' # JSTの0時、6時、12時、18時に自動再起動（UTC:15:15→JST0:15、以降6時間おき）
concurrency:
  group: discord-bot
  cancel-in-progress: true # 実行中のジョブをキャンセルして新しいジョブを起動
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Create .env file
        run: |
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
      - name: Start Bot
        run: npm start
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
